image: Visual Studio 2022

environment:
  matrix:
    - PYTHON_MAJOR: 3
      PYTHON_MINOR: 8

cache:
  - .venv -> poetry.lock

install:
  # Install system dependencies
  - choco install make
  - curl -sSL https://install.python-poetry.org | python -
  - set PATH=%USERPROFILE%\AppData\Roaming\Python\Scripts;%PATH%
  - make doctor
  # Install project dependencies
  - make install

build: off

test_script:
  - make test-repeat
